#!/usr/bin/env python
"""
Generate Elmer SIF files for a rotating diametrically-magnetised cylinder at
multiple rotation angles.  Each angle is a steady-state snapshot with the
magnetisation vector rotated by θ about the Z axis.

Rotation frequency: 5 Hz (300 RPM)

Usage:
    python rotate_scan.py [--angles N]

Outputs one SIF per angle and a batch script (run_all_angles.bat) to execute
all solves sequentially on Windows.
"""

import math
import sys
from pathlib import Path

M0 = 955000.0       # [A/m] NdFeB N35 (Br ≈ 1.2 T)
FREQ = 5.0          # [Hz]
RPM = FREQ * 60.0   # 300 RPM
OMEGA = 2.0 * math.pi * FREQ
N_ANGLES = 36       # every 10 degrees

if "--angles" in sys.argv:
    idx = sys.argv.index("--angles")
    N_ANGLES = int(sys.argv[idx + 1])

SIF_TEMPLATE = """! ══════════════════════════════════════════════════════════════════════════════
!  Rotating PM — snapshot at {angle_deg:.1f}°
!  M = ({mx:.1f}, {my:.1f}, 0) A/m    ω = {omega:.4f} rad/s ({rpm} RPM)
!  Generated by rotate_scan.py
! ══════════════════════════════════════════════════════════════════════════════

Header
  CHECK KEYWORDS Warn
  Mesh DB "." "."
  Include Path ""
  Results Directory "results_angle_{angle_deg:03.0f}"
End

Simulation
  Max Output Level = 5
  Coordinate System = Cartesian 3D
  Coordinate Mapping(3) = 1 2 3
  Simulation Type = Steady State
  Steady State Max Iterations = 1
  Output File = "case_angle_{angle_deg:03.0f}.result"
  Post File = "case_angle_{angle_deg:03.0f}.vtu"
End

Constants
  Permeability of Vacuum = 1.2566370614359173e-06
  Permittivity of Vacuum = 8.854187817e-12
End

Solver 1
  Equation = "Magnetic AV"
  Procedure = "MagnetoDynamics" "WhitneyAVSolver"
  Exec Solver = Always
  Stabilize = True
  Optimize Bandwidth = True

  Linear System Solver = Iterative
  Linear System Iterative Method = BiCGStabl
  Linear System Max Iterations = 2000
  Linear System Convergence Tolerance = 1.0e-8
  Linear System Preconditioning = ILU0

  Steady State Convergence Tolerance = 1.0e-6
End

Solver 2
  Equation = "Magnetic Field Calc"
  Procedure = "MagnetoDynamics" "MagnetoDynamicsCalcFields"
  Potential Variable = AV
  Exec Solver = Always

  Calculate Magnetic Field Strength = True
  Calculate Magnetic Flux Density = True
  Calculate Magnetic Vector Potential = True
  Calculate Nodal Fields = True
  Calculate Current Density = False
  Calculate Joule Heating = False
  Calculate Nodal Forces = False

  Linear System Solver = Iterative
  Linear System Iterative Method = CG
  Linear System Max Iterations = 1000
  Linear System Convergence Tolerance = 1.0e-8
  Linear System Preconditioning = ILU0
  Steady State Convergence Tolerance = 1.0e-6
End

Solver 3
  Equation = "Result Output"
  Procedure = "ResultOutputSolve" "ResultOutputSolver"
  Exec Solver = After Simulation

  Output File Name = "case_angle_{angle_deg:03.0f}"
  Output Format = "Vtu"
  Vtu Format = True
  Binary Output = True
  Discontinuous Bodies = True
  Save Geometry IDs = True
End

Equation 1
  Name = "Magnetics"
  Use Piola Transform = Logical True
  Active Solvers(2) = 1 2
End

Material 1
  Name = "NdFeB_N35"
  Relative Permeability = 1.05
  Magnetization 1 = {mx:.1f}
  Magnetization 2 = {my:.1f}
  Magnetization 3 = 0.0
End

Material 2
  Name = "Air"
  Relative Permeability = 1.0
End

Material 3
  Name = "Air"
  Relative Permeability = 1.0
End

Body 1
  Target Bodies(1) = 1
  Name = "Magnet"
  Equation = 1
  Material = 1
  Body Force = 1
End

Body 2
  Target Bodies(1) = 2
  Name = "AirRotating"
  Equation = 1
  Material = 2
End

Body 3
  Target Bodies(1) = 3
  Name = "AirStationary"
  Equation = 1
  Material = 3
End

Body Force 1
  Name = "MagnetizationForce"
End

Boundary Condition 1
  Target Boundaries(1) = 1
  Name = "FarField"
  AV {{e}} = Real 0
End
"""

# ── Generate SIF files ─────────────────────────────────────────────────────
MESH_DIR = Path("mesh")
MESH_DIR.mkdir(exist_ok=True)

for i in range(N_ANGLES):
    theta = 2.0 * math.pi * i / N_ANGLES
    angle_deg = math.degrees(theta)
    mx = M0 * math.cos(theta)
    my = M0 * math.sin(theta)

    content = SIF_TEMPLATE.format(
        angle_deg=angle_deg,
        mx=mx,
        my=my,
        freq=FREQ,
        omega=OMEGA,
        rpm=RPM,
    )

    fname = MESH_DIR / f"case_angle_{angle_deg:03.0f}.sif"
    fname.write_text(content)
    print(f"  wrote  {fname}   M = ({mx:.0f}, {my:.0f}) A/m")

# Also write an example SIF in the rotating_magnet root
example_sif = Path("case_rotate.sif")
if not example_sif.exists():
    theta = 0.0
    content = SIF_TEMPLATE.format(angle_deg=0.0, mx=M0, my=0.0,
                                   freq=FREQ, omega=OMEGA, rpm=RPM)
    example_sif.write_text(content)
    print(f"  wrote  {example_sif} (example — angle 0°)")

# ── Generate batch script ───────────────────────────────────────────────────
elmer_home = r"D:\Elmer\Elmer 9.0-Release"
bat_lines = [
    "@echo off",
    "REM ============================================================",
   f"REM  Run all {N_ANGLES} rotation angles for the rotating PM",
    "REM  Generated by rotate_scan.py",
    "REM ============================================================",
    "setlocal",
    "",
   f"set ELMER_HOME={elmer_home}",
    "set PATH=%ELMER_HOME%\\bin;%ELMER_HOME%\\lib\\elmersolver;%ELMER_HOME%\\stripped_gfortran\\bin;%PATH%",
    "",
    "cd /d \"%~dp0mesh\"",
    "",
    "set TOTAL=0",
    "set OK=0",
]
for i in range(N_ANGLES):
    angle_deg = i * 10
    bat_lines.append(f"echo [{i+1}/{N_ANGLES}] Solving angle {angle_deg}...")
    bat_lines.append(f"ElmerSolver.exe case_angle_{angle_deg:03d}.sif")
    bat_lines.append(f"if %ERRORLEVEL% EQU 0 (set /a OK+=1)")

bat_lines += [
    "",
    "echo ============================================================",
    "echo   Finished.",
    "echo ============================================================",
    "pause",
    "endlocal",
]

batch_path = MESH_DIR / "run_all_angles.bat"
batch_path.write_text('\n'.join(bat_lines) + '\n')
print(f"\n  wrote  {batch_path}")

print(f"\nGenerated {N_ANGLES} SIF files (0° to {(N_ANGLES-1)*10}°).")
print(f"  Frequency: {FREQ} Hz  (ω = {OMEGA:.4f} rad/s, {RPM} RPM)")
print(f"\nNext steps:")
print(f"  1. ElmerGrid 14 2 mesh.msh -out mesh -autoclean")
print(f"  2. cd mesh")
print(f"  3. Run run_all_angles.bat (or individual ElmerSolver case_angle_NNN.sif)")
print(f"  4. python ../create_pvd.py")
print(f"  5. Open rotate_animation.pvd in ParaView")
